src/objects/FW_logError__c.object
<CustomObject>
    <description>Object where system error messages will be stored</description>
    <fields>
        <fullName>FW_StackTrace__c</fullName>
        <description>Stack Trace returned by the system</description>
        <label>StackTrace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FW_aplicationCode__c</fullName>
        <description>Code of the application where the error is being generated</description>
        <label>Application Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FW_class__c</fullName>
        <description>Apex class where the error occurred</description>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FW_errorDate__c</fullName>
        <description>date the error occurs</description>
        <label>Error Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FW_errorMessage__c</fullName>
        <description>error message released by the system</description>
        <label>Error message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FW_errorUser__c</fullName>
        <description>User logged in that has produced the error</description>
        <label>Error User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FW_method__c</fullName>
        <description>Class method where the error occurs</description>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log-{000000000}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FW_errorHandler.cls
/*-----------------------------------------------------------------------------------------------------------//
* Class Name    : FW_errorHandler
* Project       : PROSEGUR - Framework
* Author        : DGS (PROSEGUR)
* Date          : 04/10/2021
* Description   : Class to save the error.
* @Public 
*               1. insertError.    				calls method to catch the exception
* @Private
*               1. errorSaveDataBase.           Insert in BBDD the error.
*-----------------------------------------------------------------------------------------------------------*/

public class FW_errorHandler {
    
     /*********************************************************************************************************
    * @Method          :   insertError
    * @Author          :   DGS (PROSEGUR)
    * @Created         :   04/10/2021
    * @Description     :   calls method to catch the exception.
    * @params   	   :   Exception. Error to catch.
    * @Returns         :   NA (void method).
    **********************************************************************************************************/
    public static void insertError(Exception e ) {
		errorSaveDataBase(e, false) ;              
    }

    /*********************************************************************************************************
    * @Method          :   errorSaveDataBase
    * @Author          :   DGS (PROSEGUR)
    * @Created         :   04/10/2021
    * @Description     :   calls method to catch the exception.
    * @params   	   :   Exception. Error to catch.
    * 				   :   Boolean. True, access to testing part.   
    * @Returns         :   NA (void method).
    **********************************************************************************************************/
    @TestVisible      
    private static void errorSaveDataBase (Exception except, boolean testing ){
        
        //------------ VARs --------------
        Boolean retCorrectInsert = true;
        String methodName = except.getStackTraceString()?.substringBefore(':')?.substringAfterLast('.');
        String className = except.getStackTraceString()?.substringBefore(':')?.substringBetween('.');
        String appCode = className?.substringBefore('_');

        
        try{
            if(Test.isRunningTest() && testing){
                throw new DMLException('FW_cls_errorHandler_test');
            }                
            insert new FW_logError__c(FW_aplicationCode__c = appCode, FW_errorDate__c = System.now(), FW_errorUser__c = Userinfo.getName(),
                                            FW_class__c = className, FW_method__c = methodName,
                                            FW_errorMessage__c = except.getMessage(), FW_StackTrace__c = except.getStackTraceString());                
            System.debug('Error insertado.');
        }
        catch(Exception e){
            System.debug('Error insertado.');
            insert new FW_logError__c(FW_aplicationCode__c = 'FW', FW_errorDate__c = DateTime.now(), FW_errorUser__c = UserInfo.getName(), 
                                                FW_class__c = e.getStackTraceString().substringBefore(':').substringBetween('.'), FW_method__c = e.getStackTraceString().substringBefore(':').substringAfterLast('.'), 
                                                FW_errorMessage__c = e.getMessage(), FW_StackTrace__c = '');     
        }       
        
    }
    
    
}